### ISSUE TITLE
Pop ups

### ISSUE THREAD

**Issue by ehomesng** [churchtools/churchtools-js-client#12]
Can we have someone program how pop-ups could be used in churchtools?

**Comment by djschilling** [comment]
@ehomesng Can you explain in more detail what you mean? i don't understand it.

**Comment by ehomesng** [comment]
Thanks for your response @djschilling The question is if we can publish or relay new information to all our users on Churchtools via a Pop-ups on opening the page?

**Comment by djschilling** [comment]
thats a question that is not related to this project.
You can send your question to support@churchtools.de or in our forum: https://forum.church.tools
